"""Constants for the BLE Gastank integration."""

DOMAIN = "ble_gastank"

CONF_SENSOR_TYPE = "sensor_type"
SENSOR_TYPE_DIMES = "dimes"
SENSOR_TYPE_TRUMA = "truma"

SENSOR_TYPES = {
    SENSOR_TYPE_DIMES: "DIMES BLE Sensor",
    SENSOR_TYPE_TRUMA: "Truma LevelControl",
}

# Manufacturer ID für DIMES (ggf. anpassen)
COMPANY_ID_DIMES = 0xFFFF

# Truma BLE UUIDs
TRUMA_SERVICE_UUID = "22BFA601-6AFE-4CC5-B3FF-3E140BAEDEB6"
TRUMA_MEASUREMENT_DATA_UUID = "22BFA610-6AFE-4CC5-B3FF-3E140BAEDEB6"
TRUMA_PASSWORD_UUID = "22BFA619-6AFE-4CC5-B3FF-3E140BAEDEB6"
